// <auto-generated />
using System;
using FIAP_Cloud_Games.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIAP_Cloud_Games.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250603121140_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("FIAP_Cloud_Games.Domain.Entities.Jogo", b =>
                {
                    b.Property<int>("IdJogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdJogo");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("FIAP_Cloud_Games.Domain.Entities.JogosUsuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdJogo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUsuario", "IdJogo");

                    b.ToTable("JogosUsuarios");
                });

            modelBuilder.Entity("FIAP_Cloud_Games.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("tipoAcesso")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FIAP_Cloud_Games.Domain.Entities.Jogo", b =>
                {
                    b.HasOne("FIAP_Cloud_Games.Domain.Entities.Usuario", null)
                        .WithMany("Jogos")
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("FIAP_Cloud_Games.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
