name: Deploy API .NET para EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    # Login no Docker Hub
    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build e push da imagem para o Docker Hub
    - name: Build e push da imagem Docker
      env:
        IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/sua-api
      run: |
        docker build -t $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:latest

    # Conectar e rodar a imagem direto do Docker Hub
    - name: Conectar e rodar comandos na EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sua-api:latest
          docker stop sua-api || true
          docker rm sua-api || true
          docker run -d -p 80:5000 --name sua-api ${{ secrets.DOCKERHUB_USERNAME }}/sua-api:latest
