name: CI - Build e Testes

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar o .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Compilar
      run: dotnet build --no-restore --configuration Release

    - name: Executar testes
      run: dotnet test --no-build --configuration Release
